# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print("NumPy Version:", np.__version__)
np.show_config()

NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
answer3 = np.zeros(10)
print(answer3, answer3.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
array = np.arange(5)
memory_size = array.size * array.itemsize
print(memory_size)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
answer5 = np.zeros(10)
answer5[4] = 1
print(answer5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
answer6 = np.arange(10,50)
print(answer6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
answer7_original = np.arange(10)
answer7_reverse = answer7_original[::-1]
print('original\n:',answer7_original,'\n\nreverse\n:', answer7_reverse)

original
: [0 1 2 3 4 5 6 7 8 9] 

reverse
: [9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [32]:
answer8 = np.arange(0,9).reshape(3,3)
print(answer8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [38]:
array9 = np.array([1,2,0,0,4,0])
answer9 = np.where(array9==0)
answer9

(array([2, 3, 5]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [42]:
#help(np.identity)
answer10 = np.identity(3)
print(answer10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [50]:
answer11 = np.random.random((3,3,3))
print(answer11, '\n\n\n', answer11.shape)

[[[0.56760963 0.15201529 0.01483184]
  [0.98000704 0.39959537 0.97173489]
  [0.96085894 0.49871664 0.42455068]]

 [[0.40705778 0.39272237 0.87134099]
  [0.83978884 0.41963541 0.02002709]
  [0.59133007 0.57595589 0.34483534]]

 [[0.53141966 0.90428291 0.42329917]
  [0.25526118 0.41169104 0.33607   ]
  [0.8420357  0.18989108 0.16073434]]] 


 (3, 3, 3)


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [62]:
array12 = np.random.random((10,10))
index12 = np.argsort(array12,axis=None)
minimum_index = index12[0]
maximum_index = index12[-1]
min_pos = np.unravel_index(minimum_index, array12.shape) #np.unravel_index는 1D 인덱스를 2D 행렬의 (행, 열) 좌표로 변환해 줌.
max_pos = np.unravel_index(maximum_index, array12.shape)
print(f'minimum_value:', array12[min_pos], f'maximum_value:', array12[max_pos])

minimum_value: 0.01065807150389464 maximum_value: 0.9935178424868428


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [69]:
array13 = np.random.random(30)
answer13 = np.mean(array13)
print(f'array:\n',array13, '\n\n', f'mean:',answer13)

array:
 [0.15826489 0.38764523 0.02712194 0.7673853  0.22318311 0.74832685
 0.02306599 0.15666092 0.71418475 0.55529457 0.65840206 0.73593086
 0.5070485  0.41041643 0.54648876 0.48627071 0.28332535 0.47712386
 0.90120618 0.4152571  0.76076034 0.96360264 0.48568952 0.15386517
 0.5035678  0.0804029  0.89026354 0.02327342 0.1492649  0.81673799] 

 mean: 0.46700105298942596


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [82]:
array2d_14 = np.ones([3,3])
array2d_14[1,1]=0
answer14 = array2d_14
print(answer14)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [92]:
array16 = np.zeros([5,5])
index16 = np.array([[1,0],[2,1],[3,2],[4,3]])
for idx, val in zip(index16, [1, 2, 3, 4]):
    array16[idx[0], idx[1]] = val
print(array16)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [99]:
array17 = np.zeros([8,8],dtype=np.int32)
array17[1::2, ::2] = 1
array17[::2, 1::2] = 1
array17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [108]:
answer18 =np.unravel_index(99,(6,7,8))
answer18

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [110]:
array19 = np.random.random((5,5))
mean = np.mean(array19,axis=None)
std = np.std(array19,axis=None)
answer19 = (array19-mean) / std
print(answer19)

[[-0.4138459   1.43379664  0.92981957 -1.09374152 -0.96312881]
 [-0.2668929   0.47934273 -0.98023106  1.34829994  0.47653102]
 [-0.52190198 -0.47244186 -1.34618362  1.37860731  0.3094561 ]
 [ 0.73282121  1.24833673 -1.38479614 -1.21191118  0.96382791]
 [ 0.50249266  1.59476462 -1.3180228  -1.04002865 -0.38497   ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [111]:
custom_dtype = np.dtype([('r', np.ubyte),
                         ('g', np.ubyte),
                         ('b', np.ubyte),
                         ('a', np.ubyte)])
colors = np.array([(255, 0, 0, 255),
                   (0, 255, 0, 255),
                   (0, 0, 255, 255)],
                  dtype=custom_dtype)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
