#[개념정리]
##**넘파이란?**  

넘파이 : 머신러닝에서 가장 중요하다고 볼 수 있는 라이브러리  
왜? : 데이터 전처리 부분에서 쓰이는 선형대수와 같은 수학적 기법을 지원해줌.  
라이브러리? : import numpy as np 로 호출  
데이터 타입? : ndarray  
shape?: ndarray의 크기, 행과 열의 수를 튜플 형태로 가지고 있고 이를 통해서 ndarray 배열의 차원까지 알 수 있음.  

###**ndarray의 데이터 타입**   

ndarray내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능함.  
dtype함수를 통해 데이터 유형을 알 수 있고, .astype()를 통해 데이터 타입을 변경할 수 있음.  

###**ndarray 편하게 생성하기 with arange(), zeros(), ones()**    

arange(10) > range(10) 과 같은 역할! > 0에서부터 함수인자에 할당된 숫자 -1까지의 수 반환, default 값이 stop이지만 start기능도 할 수 있음  
zeros() > 함수인자에 shape을 지정해주면, shape 형태의 0반환  
ones() > 함수인자에 shape을 지정해주면, shape 형태의 1반환

###**reshape()으로 차원과 크기 변경하기**  

reshape(1,2) > shape이 (1,2)인 ndarray로 반환해줌.

reshape(5,-1) > shape이 (5, 알아서 맞춰서...)인 ndarray로 반환해줌.  

reshape(-1,1) > shape... 무조건 열 하나는 갖춘 2차원 ndarray로 반환해줘  

### **행렬의 정렬 - sort()와 argsort()**  
sort() - 오름차순 default값으로 행렬을 정렬해줌.  
np.sort() - 행렬을 정렬한 값을 반환해줌, 기존 행렬 변화 x  
ndarray.sort() - 기존 행렬을 정렬해서 반환해줌  

argsort() - 행렬을 정렬하고, 그 인덱스 값을 반환해줌.  

내림차순으로 하고 싶으면 np.sort(' ')[::-1] 해주면 됨.

**numpy 는 메타 데이터를 갖지 못하기 떄문에 인덱스를 뽑아서 원하는 정보를 추출해야함 **


#[코드 필사]

##3-1. 넘파이 ndarray 개요

In [1]:
import numpy as np
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [2]:
#차원 확인하는 .ndim 함수
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,
                                                                 array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


##3-2. ndarray의 데이터 타입

In [3]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [4]:
'''
ndarray 내의 데이터들은, 데이터 타입이 같아야 하고 그렇지 않으면 데이터 타입이 더 큰 값으로 데이터 유형을 변환한다
'''

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) #데이터 타입이 더 큰 유니코드 문자열 값으로 변환

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #데이터 타입이 더 큰 실수형 값으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [5]:
'''
메모리 절약을 하기 위해 데이터 로딩할 때, float가 필요하지 않을 경우
int로 변환하기 위해 astype()을 이용
'''
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## 3-3. ndarray를 편리하게 생성하기 - arange, zeros, ones

In [6]:
#arange() > range와 같은 역할
sequence_array = np.arange(10)
sequence_array = sequence_array.astype('int32') #책의 답과 맞춰주기 위해 코드 추가
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


#default 값은 stop 이나 range 와 같이 start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있음
#sequence_array2 = np.arange(2,10)
#print(sequence_array2)


[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [7]:
#zeros()와 ones() >함수인자로 튜플 형태의 shape 값을 입력하면 0과 1로 shape 만큼 채워서 반환
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#dtype 지정해주지 않으면 float로 반환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


##3-4. ndarray의 차원과 크기를 변경하는 reshape()

In [8]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array2.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
#지정된 사이즈로 변경이 불가능하면 오류를 발생함
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [10]:
#reshape() 함수인자에 -1을 적용하는 경우
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [12]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##3-5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

In [13]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10).astype('int32') #반환 값 같게 하려고 코드 추가...
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [14]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [15]:
#인덱싱 통해 수정도 가능
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [16]:
#다차원의 ndarray에서 데이터 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


##3-6. 넘파이의 ndarray의 데이터 세트 선택하기 - 슬라이싱

In [17]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:] #자동으로 처음부터 끝까지
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [19]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3,0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3,:]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:, :])
print('array2d[:2,1:]\n', array2d[:2, 1:])
print('array2d[:2,0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [20]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


##3-7. 넘파이의 ndarray의 데이터 세트 선택하기 - 팬시 인덱싱

In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


##3-8. 넘파이의 ndarray의 데이터 세트 선택하기 - 불린 인덱싱

In [22]:
array1d = np.arange(start=1, stop=10)
#[ ] 안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d >5 불린 인덱싱 결과 값:', array3)

array1d >5 불린 인덱싱 결과 값: [6 7 8 9]


In [23]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [24]:
#불린 값을 직접 대입해도 됨
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [25]:
#인덱스 집합을 만들어 대입해도 됨.
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

#중요한 것은 인덱스의 특정 값을 저장하는 게 아니라, 인덱스 값을 저장한다는 것

일반 인덱스로 필터링 결과: [6 7 8 9]


##3-9. 행렬의 정렬 - sort()와 argsort()

In [28]:
org_array = np.array([3,1,9,5])
print('원본 행렬', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬 [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [30]:
#다차원일 때
array2d = np.array([[8,12],
                   [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


##3-10. 정렬된 행렬의 인덱스를 반환하기

In [31]:
#원본 행렬 인덱스를 ndarray 형으로 반환함.
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
#내림차순
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##3-11. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [34]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [35]:
#transpose()이용해서 전치행렬 구하기
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
